### ISSUE TITLE
[MapRender] Incorrect color appearance

### ISSUE THREAD

**Issue by Sunaries** [KENNYSOFT/WzComparerR2#1]
Repost as requested:

The localized version you released does not have a 100% working map render.
If I render the map 헤네시스 (ID: 100000000), I will have the following render saved:

![20161010095016307_100000000_korean](https://cloud.githubusercontent.com/assets/11575591/19229726/141ae3a6-8ed0-11e6-8d73-8515ef90f14e.png)

While the original program renders and saves it with the correct colors, like this:

![20161010095646336_100000000_goodver](https://cloud.githubusercontent.com/assets/11575591/19229744/2ac4c7a2-8ed0-11e6-8e19-ef1cb89d898a.png)

To save a map render, you press Scroll Lock key while the map render is active.

Developer's response: https://github.com/Kagamia/WzComparerR2/pull/8#issuecomment-252576716

**Comment by KENNYSOFT** [comment]
Resolved in 9aef4992707dd0f06e4d4bc97e240ee663e91a70
