### ISSUE TITLE
안녕하세요. 의자 이미지 관련 질문 드립니다. 

### ISSUE THREAD

**Issue by jellysz** [KENNYSOFT/WzComparerR2#10]
안녕하세요. 덕분에 좋은 프로그램 잘 쓰고 있습니다. 

의자 아이콘 이미지는 있는데, 아이템 이미지를 찾을 수가 없더라구요..
아직 위컴알을 이용해서 의자의 이미지는 저장할 수 없는건가요?? 

항상 감사드립니다.

**Comment by KENNYSOFT** [comment]
안녕하세요.

의자 이미지의 위치는 의자의 종류에 따라 다릅니다. 이는 의자 구현 방식이 여러 가지라서 그렇습니다.

일반적인 의자의 경우 대부분 그 아이템 내부에 이미지가 있습니다만, TamingMob이나 라이딩 스킬 방식으로 구현되어 있는 의자도 있을 수 있으니 해당 부분 코드들과 해당 노드에 가서 살펴보시면 나올 것입니다.

감사합니다.

**Comment by jellysz** [comment]
<img width="669" alt="20171016_210844" src="https://user-images.githubusercontent.com/32809704/31611231-458b4240-b2b6-11e7-9197-ac7b24843d28.png">

번거롭게 해드려서 죄송하지만, 라이딩 스킬에서도 제가 아이콘 이미지밖에 찾질 못해서요..
프로그램에 없는 것이 아니라 제가 프로그램에서 이미지를 못 찾고 있다는 생각이 들었습니다.
혹시 괜찮으시다면 어디에서 찾을 수 있는지 알려주실 수 있을까요??

감사합니다.

**Comment by KENNYSOFT** [comment]
저 라이딩의 경우 찾으신 2431700 아이템은 '이용권' 아이템이니, 해당 라이딩 스킬 항목인 80001261로 가서 찾아보시는 것이 맞습니다. 이 스킬의 경우 해당 노드에 나와있지는 않지만, 수동으로 찾아보면 아래와 같이 Character.wz\TamingMob\01932164.img에 이미지들이 있습니다.

![image](https://user-images.githubusercontent.com/6624567/31646006-1fd00a84-b33a-11e7-89ec-de084e9b9c5d.png)

**Comment by KENNYSOFT** [comment]
한편 보너스로 여기서 아이디어를 얻어 만든 신기능의 티저 이미지를 보여드립니다. https://github.com/KENNYSOFT/WzComparerR2/commit/f641de4d98e3af5dfaf51bd431832b1f1a7ed88f

![01932164 img walk1 0](https://user-images.githubusercontent.com/6624567/31660254-d3ec3312-b371-11e7-8d2a-4fe5b76a9fd1.gif)

![01932164 img stand1 0](https://user-images.githubusercontent.com/6624567/31660348-149cd466-b372-11e7-91b0-f5bba5a22cf4.gif)

![01932164 img prone 0](https://user-images.githubusercontent.com/6624567/31660351-1550820e-b372-11e7-9bbd-510565106ece.gif)

**Comment by jellysz** [comment]
덕분에 의자, 라이딩 이미지를 찾는데 도움이 되었습니다. 정말 감사드립니다.
