### ISSUE TITLE
Graph.img가 없는 클라이언트에서 맵 렌더 오류

### ISSUE THREAD

**Issue by seotbeo** [KENNYSOFT/WzComparerR2#102]
빅뱅 전 등의 과거 클라이언트에서 Graph.img가 없는 경우에
`PluginManager.FindWz("Map/Map/Graph.img")`가 null이 되면서 오류가 발생합니다
미리 확인 못해서 죄송합니다

`MapData.cs Line 334`:
`foreach (var graphImgSubNode in PluginManager.FindWz("Map/Map/Graph.img").Nodes)`

**Comment by KENNYSOFT** [comment]
혹시나 했었는데 역시나네요.

https://github.com/KENNYSOFT/WzComparerR2/blob/88a907b00be6896a5cdf6b65dff2331b9acfaec5/WzComparerR2.MapRender/FrmMapRender2.cs#L820

이런 처리가 있어야겠군요.

빅뱅 전 등 과거 클라이언트가 어딘가에는 있을텐데... 찾아서 테스트 해보겠습니다.
