### ISSUE TITLE
[KMST 1.2.149] 장비 툴팁 공격속도 표기

### ISSUE THREAD

**Issue by seotbeo** [KENNYSOFT/WzComparerR2#113]
KMST v1.2.149 업데이트로 공격속도에 (10-value단계) 표기가 추가되었어요
      
https://github.com/KENNYSOFT/WzComparerR2/blob/63fa1d72756dc8294cd6648d10619f2d048567da/WzComparerR2/CharaSimControl/GearTooltipRender2.cs#L517

![Maple_221216_221949](https://user-images.githubusercontent.com/101188238/208108504-c700d4b3-f66f-4e10-9a4f-f84dbfc49771.png)
![Maple_221216_222502](https://user-images.githubusercontent.com/101188238/208108514-7eb414c2-5cff-43f9-9b44-252dfda64dfd.png)

![1404000](https://user-images.githubusercontent.com/101188238/208108520-b86118a2-75b2-418d-b1da-476f822f1f7d.png)

**Comment by KENNYSOFT** [comment]
seotbeo@2b1d3d753d8c6e69a21b990cf0c4225a2e2b7bc8

**Comment by seotbeo** [comment]
저건 제 편의에 맞게 바꾼게 많아서..ㅠㅠ 참고만 해주시면 감사하겠습니다
