### ISSUE TITLE
Better Saving Format for Avatar

### ISSUE THREAD

**Issue by Dban1** [KENNYSOFT/WzComparerR2#12]
It'd be really amazing if the Avatar Save portion could be expanded upon to allow saving in the PNG format or frame by frame. Because right now, the gif format alone does not support semi-transparency and the resulting export gifs look too thick in the transparent parts

**Comment by KENNYSOFT** [comment]
Exporting Avatar to APNG is already supported from KMS-v3.0.0.

**Comment by Dban1** [comment]
Ah, that's great!! Thanks
