### ISSUE TITLE
안녕하세요. 맵 랜더에 관해 질문하겠습니다.

### ISSUE THREAD

**Issue by Crown2000** [KENNYSOFT/WzComparerR2#13]
맵 미리보기 기능을 이용해서 맵을 볼려고 하면 아래의 메세지가 뜨면서 아예 열리지가 않습니다.
무엇이 원인인지를 모르겠습니다. 문제를 해결해주시면 감사하겠습니다.

******** MapRender *********
System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
위치: WzCompareR2.MapRender.FrmMapRender2.UnloadContent()
위치: WzCompareR2.MapRender.FrmMapRender2.Dispose(Boolean disposing)
위치: Microsoft.Xna.Framework.Game.Disepose()
위치: WzCompareR2.MapRender.FrmMapRender2.Entry.<>c__DisplayClass5_1.<btnItem_Click>b__0()

**Comment by KENNYSOFT** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=20914 설치하고 다시 시도해 보세요.

**Comment by Crown2000** [comment]
고맙습니다! ^^
