### ISSUE TITLE
cant open MSEA V225 file

### ISSUE THREAD

**Issue by Jancy-49** [KENNYSOFT/WzComparerR2#130]
![image](https://github.com/KENNYSOFT/WzComparerR2/assets/58067113/57a7c1ce-dfae-4bd3-91b3-33bf8cf2ba27)

**Comment by KENNYSOFT** [comment]
Kagamia@10edeef87da22b206aa58fdd1ee3d7927a658bc4

**Comment by KENNYSOFT** [comment]
Resolved in 3a780483951d0a2f4edfe4974a0f6f3407e55547
