### ISSUE TITLE
Addition Tooltip for Equipment: "hideDesc" not properly hiding the tooltip

### ISSUE THREAD

**Issue by PirateIzzy** [KENNYSOFT/WzComparerR2#131]
In KMST 1.2.162, a few items with "Addition" details had the `hideDesc` parameter added, which should place the details near the bottom of the equipment tooltip, hiding the side tooltip. One example being 1114312:

![Screenshot 2023-10-22 203956](https://github.com/KENNYSOFT/WzComparerR2/assets/34289651/9c71d522-75a2-4f94-8c2c-ac56e6395051)

This is how it appears in game, without the "Addition" tooltip on the side:
![adventure-deep-dark-critical-ring](https://github.com/KENNYSOFT/WzComparerR2/assets/34289651/251b147b-2bfa-429c-b109-156ae9aeb53a)

However, WCR2 displays the details near the bottom of the equipment tooltip + in the side tooltip, since they added `desc` strings for it:
![1114312](https://github.com/KENNYSOFT/WzComparerR2/assets/34289651/e0909297-6618-4ff8-9f5c-4e61d8ad8fba)
![image](https://github.com/KENNYSOFT/WzComparerR2/assets/34289651/5c5bb818-1049-42bf-86c7-62333afce530)

**Comment by KENNYSOFT** [comment]
> ■ 일부 반지 띄어쓰기와 이름이 변경되고, 능력치 설명이 더 잘 보이게 개선됩니다.

https://www.youtube.com/watch/?v=sMPNSau6Z18&t=7526

> 이제 그 다음에 그 능력치 설명 보면은 예전에 그 그 뭐야 그 쓰읍 아 헌터스 링 어 그 사냥 반지 일몹뎀 같은 경우에 이제 우측에 이렇게 좀 삐져나와 있었잖아요? 그 크리티컬 링도 마찬가지고 이제 고런 것들을 좀 더 예쁘게 이제 하단에 이렇게 붙여가지고 어 표현했다 이렇게 봐주시면은 될 것 같습니다.

**Comment by PirateIzzy** [comment]
In this case, I think the best approach would be to suppress/hide the Addition tooltip if the "hideDesc" parameter is present under `addition`:

![image](https://github.com/KENNYSOFT/WzComparerR2/assets/34289651/a8085e2e-0b85-4b8c-a9f9-6646d7b0ac78)

**Comment by Kagamia** [comment]
Support via https://github.com/Kagamia/WzComparerR2/commit/a874412105a34400340c6302ce1aa3519a74f41c
