### ISSUE TITLE
인형핑크를 낀 상태에서 hit 얼굴을 보려고 하면 위컴알이 멈춰버립니다. 

### ISSUE THREAD

**Issue by giraffebin** [KENNYSOFT/WzComparerR2#14]
안녕하세요, 위컴알 잘 애용중인 유저입니다. 다만 얼굴 감정 표현들 확인 도중 인형 핑크 + 찡그린 얼굴 (hit 얼굴)을 하게 되면 위컴알이 멈추며 튕겨버립니다. 몇달째 겪는 상황인데 이번 업데이트에도 수정되지 않아 글 작성해보게 되었습니다.

**Comment by KENNYSOFT** [comment]
안녕하세요. 제보해주신 내용 잘 확인했습니다.
본 사항은 인형핑크(1012083)에서 hit이 blink를 거쳐 default로 가는 이중 Uol 구조인데 해당 반복문이 잘못 짜여있어 발생한 오류였습니다. 모든 아이템의 모든 동작을 확인해볼 수가 없어서 놓쳤던 부분입니다.

이를 수정한 커밋을 푸시하고 (https://github.com/KENNYSOFT/WzComparerR2/commit/2b88e5d13856366d3b03a0af07cb98c8ed348bbc) 원 저장소에 버그 리포트를 완료했습니다. (https://github.com/Kagamia/WzComparerR2/issues/111)

![image](https://user-images.githubusercontent.com/6624567/59680142-9c888900-920b-11e9-88a5-8222d1e39790.png)

다만 릴리즈 주기 계획상 바로 바이너리를 제공하지는 않고, 추후 버전에 이 픽스가 포함될 예정입니다. 직접 컴파일하셔서 사용하실 수도 있고, 꼭 필요하다면 댓글 달아주시면 이 이슈에 따로 현재 빌드를 올려드리겠습니다.

저 혼자 테스트를 하기 어렵다 보니 놓치는 부분들이 많은데 제보해 주셔서 감사합니다. 앞으로는 버그 사항 있으면 바로바로 알려주세요!
