### ISSUE TITLE
Cash packages preview error

### ISSUE THREAD

**Issue by lowrt** [KENNYSOFT/WzComparerR2#15]
The latest compilation seems to have a problem?

> System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
> 
>    System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    WzComparerR2.CharaSimControl.CashPackageTooltipRender.RenderCashPackage(Int32& picH)
>    WzComparerR2.CharaSimControl.CashPackageTooltipRender.Render()
>    WzComparerR2.CharaSimControl.ItemTooltipRender2.RenderCashPackage(CashPackage cashPackage)
>    WzComparerR2.CharaSimControl.ItemTooltipRender2.Render()
>    WzComparerR2.CharaSimControl.AfrmTooltip.PreRender()
>    WzComparerR2.CharaSimControl.AfrmTooltip.Refresh()
>    WzComparerR2.MainForm.quickView(Node node)
>    WzComparerR2.MainForm.advTree2_AfterNodeSelect_2(Object sender, AdvTreeNodeEventArgs e)
>    DevComponents.AdvTree.AdvTreeNodeEventHandler.Invoke(Object sender, AdvTreeNodeEventArgs e)
>    DevComponents.AdvTree.AdvTree.OnAfterNodeSelect(AdvTreeNodeEventArgs args)
>    DevComponents.AdvTree.AdvTree.SelectNode(Node node, eTreeAction action)
>    DevComponents.AdvTree.AdvTree.ٹ(Node ْ, MouseEventArgs ؾ, Point ٧)
>    DevComponents.AdvTree.AdvTree.OnMouseDown(MouseEventArgs e)
>    System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>    System.Windows.Forms.Control.WndProc(Message& m)
>    System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>

**Comment by KENNYSOFT** [comment]
Thanks for the report. Actually, there was a typo in April 2018.

https://github.com/KENNYSOFT/WzComparerR2/commit/12baecf19e4f69ba5dfaf5825d75cf30eba410f0#diff-35c92ea4e0ee3f812144ad0c05824fc3R95

And recently I just used that function without checking it.

https://github.com/KENNYSOFT/WzComparerR2/commit/8b412a234979de3700a85c368ae74664f660a3be#diff-b84c040956231ce269e5b23e11c89c7bR2587

So I just resolved it in https://github.com/KENNYSOFT/WzComparerR2/commit/b230709a09527d99570352a1ffc5395a882ac38d. Enjoy yourself!

![image](https://user-images.githubusercontent.com/6624567/60126080-287c5100-97c8-11e9-8019-c04337cd1918.png)
