### ISSUE TITLE
Maprender에서 뒷배경이 보이지 않습니다.

### ISSUE THREAD

**Issue by Bsctt** [KENNYSOFT/WzComparerR2#18]
![F8D14EA6-9328-47E1-8BA9-E7C3339F4A8F](https://user-images.githubusercontent.com/56929659/67410605-4e3f2880-f5f7-11e9-9565-410bb0abd0b8.png)
![7885B679-FEBB-4B8A-B7E5-533A5CCD99AF](https://user-images.githubusercontent.com/56929659/67410606-4ed7bf00-f5f7-11e9-88ca-6d59e0ebee65.png)

사진과 같이, 상당수의 맵에서 가장 뒷배경인 부분이 보이지 않습니다. 설정창 및 단축키는 정상적으로 작동하나 위와 같이 뒷배경이 보이지 않는 맵에서는 단축키 Ctrl+1이 작동하지 않습니다. 해결할 방법이 있을까요? 가장 최근 버전인 v.3.1.1을 사용하고 있습니다.

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/67998281-3cb2ec00-fc9b-11e9-8f86-19c79c1c3565.png)

Wz 분할 자동 감지 기능이 켜져 있는지 확인해보세요.

**Comment by Bsctt** [comment]
첨부해주신 사진처럼 설정했음에도 문제점이 해결되지 않습니다. 혹시 다른 원인이 있을까요?

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/90403892-92e30580-e0dc-11ea-9df2-ee3673592188.png)

안타깝지만 전혀 재현이 되지 않아 이슈를 닫습니다.
