### ISSUE TITLE
이번 신캐릭 아델 여성 얼굴이 출력되지 않습니다. 

### ISSUE THREAD

**Issue by giraffebin** [KENNYSOFT/WzComparerR2#21]
남성 아델 얼굴은 위컴알에서 정상 출력되나, 여성 아델 얼굴은 정상적으로 출력되지 않습니다.

**Comment by KENNYSOFT** [comment]
제보 감사합니다. 확인해 보겠습니다.

**Comment by KENNYSOFT** [comment]
c66296f528d42ae6fc04031e0c43c570c4b73e3b

5xxxx 코드를 사용하는 얼굴 타입이 새로 추가되어서 그런 것이었습니다. 장비 지원과 함께 릴리즈하겠습니다.
