### ISSUE TITLE
bdR / imdR tooltip icon

### ISSUE THREAD

**Issue by Sunaries** [KENNYSOFT/WzComparerR2#3]
Hiya,

![KMS ver](https://cdn.discordapp.com/attachments/236180502200057856/244441328925016064/1432167.png)

The icons are not consistent. The second icon 'Magic DEF' should be removed since it is not used in the game anymore.

It should look like this:

![GMS ver](https://cdn.discordapp.com/attachments/90616424141189120/244441007427551234/1432167_FIXED.png)
(I used GMS database as reference)

To fix this go to **WzComparerR2/CharaSimControl/GearTooltipRender2.cs** at line 1142:

```
 private void DrawPropDiffEx(Graphics g, int x, int y)
        {
            int value;
            string numValue;
            //Defense tooltip icon
            g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_pdd, x, y);
            x += 62;
            DrawReqNum(g, "0", NumberType.LookAhead, x - 5, y + 6, StringAlignment.Far);

            //Boss DMG tooltip icon
            g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_bdr, x, y);
            x += 62;
            this.Gear.Props.TryGetValue(GearPropType.bdR, out value);
            numValue = (value > 0 ? "+ " : null) + value + " % ";
            DrawReqNum(g, numValue, NumberType.LookAhead, x - 5, y + 6, StringAlignment.Far);

            //Ignored Monster DEF tooltip icon
            g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_igpddr, x, y);
            x += 62;
            this.Gear.Props.TryGetValue(GearPropType.imdR, out value);
            numValue = (value > 0 ? "+ " : null) + value + " % ";
            DrawReqNum(g, numValue, NumberType.LookAhead, x - 5, y + 6, StringAlignment.Far);
```

And remove in **CharaSimResource\Resource.resx**:

`<data name="UIToolTip_img_Item_Equip_Summary_icon_mdd" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>Resources\UIToolTip.img.Item.Equip.Summary.icon.mdd.png;System.Drawing.Bitmap, System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
  </data>`

**Comment by KENNYSOFT** [comment]
Resolved in https://github.com/KENNYSOFT/WzComparerR2/commit/3886e59a4b1a3b42348a22808343687a66995533
