### ISSUE TITLE
기본 오픈 해상도를 크게 조정할 방법이 없을까요

### ISSUE THREAD

**Issue by giraffebin** [KENNYSOFT/WzComparerR2#38]
![image](https://user-images.githubusercontent.com/50972313/72612565-7fb65e80-3970-11ea-8d45-5aaf13e856d3.png)

매번 시작하면 화면이 너무 작게 시작하는데, 기본적으로 틀 모양과 창 크기를 늘리게 설정하는 방법이 없을까요? 전체화면으로 쓰기엔 너무 커서 화면 반 정도만 먹게 윈도우 화살표로 늘려줘도 아래사진처럼 제일 중요한 목록 보는 부분이 매번 작아서 사용할 때마다 아쉬움을 느낍니다.

+ 위컴알 자체에는 믹염 기능과 이펙트 보는 기능이 현재 미지원인 것이 맞나요? 

![image](https://user-images.githubusercontent.com/50972313/72612624-a96f8580-3970-11ea-8f7c-2f61e7a70fa8.png)

**Comment by KENNYSOFT** [comment]
> 매번 시작하면 화면이 너무 작게 시작하는데, 기본적으로 틀 모양과 창 크기를 늘리게 설정하는 방법이 없을까요? 전체화면으로 쓰기엔 너무 커서 화면 반 정도만 먹게 윈도우 화살표로 늘려줘도 아래사진처럼 제일 중요한 목록 보는 부분이 매번 작아서 사용할 때마다 아쉬움을 느낍니다.

현재 창 크기가 하드코딩 되어 있어 각자의 선호에 맞추기에는 어려움이 있습니다.

> * 위컴알 자체에는 믹염 기능과 이펙트 보는 기능이 현재 미지원인 것이 맞나요?

현재 제가 배포하는 버전에서는 맞습니다. MixEff 브랜치에 지원 코드 자체는 있으니 그 코드를 사용하시면 됩니다.
