### ISSUE TITLE
The update process error occurs in the alignment

### ISSUE THREAD

**Issue by lowrt** [KENNYSOFT/WzComparerR2#39]
![QQ图片20200401222125](https://user-images.githubusercontent.com/37591855/78149048-1ec6fe80-7468-11ea-882f-73d646a37ff3.png)
Update the first 3 (map, map001, map2)
4 after update (map, map001, map002, map2)

Possible merge match error
![QQ图片20200401222146](https://user-images.githubusercontent.com/37591855/78149064-238bb280-7468-11ea-9fea-32388557c8f9.png)
![QQ图片20200401222142](https://user-images.githubusercontent.com/37591855/78149055-21295880-7468-11ea-93fc-361ca92b55b1.png)

**Comment by KENNYSOFT** [comment]
I want to test but I don't have any sample of them.. Can you send me the prior client and a patch file?

**Comment by KENNYSOFT** [comment]
> I want to test but I don't have any sample of them.. Can you send me the prior client and a patch file?

Successfully got TMS223 and MaplePatch223to224.exe

**Comment by KENNYSOFT** [comment]
링크로 바뀌거나 링크에서 바뀌는 경우 등에서 Wz_File을 지정해주지 않아 이미지를 못 얻어오는 오류 발생

![image](https://user-images.githubusercontent.com/6624567/90674030-8523b080-e293-11ea-81d3-ca57ebf01568.png)
