### ISSUE TITLE
Issue when simulating Cash Packages

### ISSUE THREAD

**Issue by Sunaries** [KENNYSOFT/WzComparerR2#4]
For GMS version, I've encountered a few crashes during debugging when selecting different packages.

**Error:**

> An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll
> 
> Additional information: The given key was not present in the dictionary.

at line 76 of CashPackageRender.cs:

`Commodity commodity = CharaSimLoader.LoadedCommoditiesBySN[CashPackage.SN[i]];`

Also, how can one edit the height between the description and line?

![Issue](https://cdn.discordapp.com/attachments/236180502200057856/265507807883689984/9102410.png)

**Comment by KENNYSOFT** [comment]
Hmm.. I think that "Flower Heir Package" is not available now. The 'commodity' is something different with common items; a commodity is identified with SN and declared in "Etc\Commodity.img", and also it can be easily gone. (Also it changes a lot in client patches.) So I think that's just an old package and GMS client doesn't have its info anymore.

Also, (by the way, that package doesn't have any item in package, so I don't know why its needed,) you can edit the height between the description and line in CashPackageRender.cs:192.

`picH -= 4;`

**Comment by Sunaries** [comment]
@KENNYSOFT The "Flower Heir Package" was just an example to showcase the height issue. Thank you. :)
