### ISSUE TITLE
샤레니안 스탠딩 일러 오류

### ISSUE THREAD

**Issue by lilyroyal** [KENNYSOFT/WzComparerR2#42]
![스크린샷(13)](https://user-images.githubusercontent.com/68749836/89422690-9f786d00-d770-11ea-8c2f-b45482b62482.png)

샤레니안 등장인물들의 일러스트가 나오지 않는 오류가 있습니다.

**Comment by KENNYSOFT** [comment]
PNG format 257 이슈

https://discordapp.com/channels/398087600428285954/398087600428285956/736260808706621513
https://discordapp.com/channels/398087600428285954/398087600428285956/737660663702224916

Kagamia/WzComparerR2#138

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/90408034-3c78c580-e0e2-11ea-8c04-79351e5a96f4.png)

upstream merge로 고쳐짐
