### ISSUE TITLE
툴팁 공백 출력 문제

### ISSUE THREAD

**Issue by sh-cho** [KENNYSOFT/WzComparerR2#54]
![diff](https://user-images.githubusercontent.com/11611397/92138095-ea0d0800-ee48-11ea-9927-6bf073e044d5.png)

---
- 대상: `Skill\15112.img\151121004` 다이크, `Skill\15112.img\151121001` 그레이브 등

툴팁에서 매 줄마다 맨 앞부분에 공백이 있을 때 공백이 출력이 됩니다.

인게임에서는 흰색 글씨는 줄 맨앞의 공백이 없어지고, 주황색 글씨 부분은 맨 앞에 공백이 있어도 출력되는듯 합니다

**Comment by KENNYSOFT** [comment]
네 거의 맞는 것 같네요.

![image](https://user-images.githubusercontent.com/6624567/92143375-2bed7c80-ee50-11ea-9931-cba5d066c350.png)

주황색 다음 칸까지도 적용이 되나 봅니다.
