### ISSUE TITLE
캐시 아이템 패키지가 제대로 출력되지 않는 오류

### ISSUE THREAD

**Issue by OniOniOn-** [KENNYSOFT/WzComparerR2#65]
![image](https://user-images.githubusercontent.com/6011621/102003360-cf9cd180-3d49-11eb-95b2-3b9fd35da509.png)

[9104992] [BTS] 시그니처 패키지도 동일한 오류가 있습니다.
구성품이 2줄로 출력되고 홀수 개면 오른쪽 줄 기준으로 아래 총 가격의 위치가 정해지는 것 같습니다.

**Comment by KENNYSOFT** [comment]
위에 아이템 이름과 판매기간 사이도 언젠가부터 몇 px 떨어지게 되었네요, 그것과 같이 보겠습니다.

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/102642482-17d04f80-41a1-11eb-8ce3-01ff93fe1888.png)

![image](https://user-images.githubusercontent.com/6624567/102642572-41897680-41a1-11eb-8fc6-73001c7ce713.png)

![image](https://user-images.githubusercontent.com/6624567/102643704-fd977100-41a2-11eb-900e-fc0bc03163ec.png)

할인율 Far이 아니라 Near, 할인율 자리수에 따라서 달라지는 것도 아님

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/102644209-c4133580-41a3-11eb-8961-5eede57e5028.png)

![image](https://user-images.githubusercontent.com/6624567/102644231-c9708000-41a3-11eb-8a98-7793548bd6e7.png)
(출처 https://blog.naver.com/nrzzzzzz/221625288444)

bonus가 아니라 할인일 때에도 적절하게 처리하여 width 확장 필요

**Comment by KENNYSOFT** [comment]
termStart가 없는데도 값이 나오는 패키지들이 있음, 완전히 없을 경우에 폭이 좁은 패키지는 줄바꿈을 어떻게 처리할 지 확인 필요
