### ISSUE TITLE
I would like to ask something. 

### ISSUE THREAD

**Issue by Chocobin** [KENNYSOFT/WzComparerR2#7]
To take a picture of the map, we should use a scroll lock key. 

But my laptop doesn't have a scroll lock key, so I can't take a picture of the map. Is there another way to take a picture?

**Comment by KENNYSOFT** [comment]
You can use 'On-Screen Keyboard' application. It has scroll lock key, like below picture.

![image](https://user-images.githubusercontent.com/6624567/30246082-62ab463e-962a-11e7-916e-229249944334.png)
