### ISSUE TITLE
패쳐기능 사용 시 스트림의 끝을 넘어 읽을 수 없습니다. 오류

### ISSUE THREAD

**Issue by Douce1** [KENNYSOFT/WzComparerR2#79]
![image](https://user-images.githubusercontent.com/90306013/132457729-2c925dea-6987-4575-859c-44ef00e162cb.png)

패쳐기능에서 패치파일, 메이플스토리 폴더를 열고, 패치를 시작하면
System.IO.EndOfStreamException: 스트림의 끝을 넘어 읽을 수 없습니다.
위치: System.IO.__Error.EndOfFile()
위치: System.IO.BinaryReader.FillBuffer(Int32 numBytes)
위치: System.IO.BinaryReader.ReadInt32()
위치: WzComparerR2.Pather. WzPatcher.CalcNewFileLength(PatchPartContext patchPart, BinaryReader reader)
위치: WzComparerR2.Patcher.WzPatcher.PrePatch()
위치: WzComparerR2.FrmPatcher.ExecutePatch(String patchFile, String msFolder, Boolean prePatch)

이렇게 뜨면서 오류가 뜨면서 패치가 취소 됩니다.
올해 6월까진 잘 됬었는데 7월 즈음부터 이럽니다 ...

**Comment by KENNYSOFT** [comment]
패치 파일의 구조가 KMST 1.2.125 부터 달라져서 그런 것으로, KMS-v3.4.3 까지는 정상 동작입니다.

해당 구조 지원을 추가한 신규 버전을 준비하고 있습니다. (ex. 7653fcf2ebb3ec7148144254780f650ada18d0e2)
