### ISSUE TITLE
A question about avatar save

### ISSUE THREAD

**Issue by tanyoucai** [KENNYSOFT/WzComparerR2#8]
Thank you for providing such useful software。I find a problem，when I use avtaer save fuction，tamingmob layers unable to save，although I know tamingmob layers and character action layers are all the independent layers，so I want to add separate tamingmob layers save fuction 。

**Comment by KENNYSOFT** [comment]
I'm afraid that I couldn't make that function. And also I think this issue should posted in original repository. https://github.com/Kagamia/WzComparerR2/issues Here you go.
