### ISSUE TITLE
ver1.2.354 클라이언트 패치로 인한 오류

### ISSUE THREAD

**Issue by nanpuhaha** [KENNYSOFT/WzComparerR2#81]
기존에는 Base.wz를 열면 Character.wz 부터 UI.wz 까지 전부 열어보고 검색도 할 수 있었지만
ver1.2.354 클라이언트 패치로 인해 Base.wz를 열어도 텅 비어 있고 검색도 동작하지 않습니다.

이는 ver1.2.354 클라이언트 패치로 인해 
기존에 C:\Nexon\Maple 디렉토리에 Base.wz 를 포함하여 모든 wz 파일들이 있었던 구조에서
패치 이후 C:\Nexon\Maple\Data 디렉토리가 새로 생기고 커다란 파일 하나로 묶여있던 wz 파일들이 여러 하위 폴더로 구성된 구조로 바뀌면서 오류가 발생한 것 같습니다.

**Comment by KENNYSOFT** [comment]
Wz 파일의 구조가 KMST 1.2.125 부터 달라져서 그런 것으로, KMS-v3.4.3 까지는 정상 동작입니다.

해당 구조 지원을 추가한 신규 버전을 준비하고 있습니다. (ex. 7653fcf)
