### ISSUE TITLE
이펙트 이미지 추출 Lua 스크립트

### ISSUE THREAD

**Issue by nanpuhaha** [KENNYSOFT/WzComparerR2#83]
사운드 추출 스크립트 외에 "이펙트 애니메이션 이미지 추출 Lua 스크립트"도 부탁 드려도 될까요?
https://github.com/Kagamia/WzComparerR2/issues/170

작성해주신 스크립트까지 3개의 Lua 스크립트 샘플과 프로젝트의 C# 코드를 보면서 `Wz_Image`들 중에서 하위 `Wz_Png`에 `delay`가 있는 노드들만 진행하면 될 것 같아 나름 하나씩 출력해가며 시도해봤는데  C#이랑 Lua가 둘 다 낯설어서 그런지 어렵네요..
`OnSaveGifFile()`, `SaveAsGif()`, `GifEncoder` 등을 써야될 것 같고, APNG를 위해서는 `encoderID = 2`로 해야될 것 같은데...

애니메이션 설정값은 아래 이미지처럼 GIF 말고 APNG로 해주시면 감사하겠습니다. (인코더 = Apng Encoder)

감사합니다.

![2021-10-03 16;41;42 1633246902](https://user-images.githubusercontent.com/9074297/135750643-0cfc2cfc-aac7-4a75-b549-a648ec069534.png)

**Comment by KENNYSOFT** [comment]
Upstream에서 f/u
