### ISSUE TITLE
GearTooltipRender: Support potential blocked message

### ISSUE THREAD

**Issue by KENNYSOFT** [KENNYSOFT/WzComparerR2#86]
### 대상

* 업그레이드 가능 횟수(`tuc`)가 0이거나 entry 자체가 없는 장비
* 잠재능력 재설정 불가(`fixedPotential`) 설정된 장비

### 미리보기

![image](https://user-images.githubusercontent.com/6624567/147377320-7ce7e41a-949a-433a-8c8e-b02a9e97fa70.png)

![image](https://user-images.githubusercontent.com/6624567/147377279-4c65c742-d9bd-410f-a025-e2c84ed55929.png)

### 참고

![image](https://user-images.githubusercontent.com/6624567/147377314-cd65f0cd-d93c-475e-8589-1d5a1242b5d6.png)

![image](https://user-images.githubusercontent.com/6624567/147377288-fee0f6a2-1a8f-471b-b1df-7127c6cbee5b.png)

[KMS 1.2.357](https://maplestory.nexon.com/news/update/653)

> ■ 잠재능력 부여, 혹은 재설정이 불가능한 장비 아이템의 하단에 '잠재능력 설정 불가'로 안내하도록 변경됩니다.
> ■ 에디셔널 잠재능력 부여가 불가능한 장비아이템의 하단에 '에디셔널 잠재능력 설정 불가'로 안내하도록 변경됩니다.

### 수정

* (Draft) `tuc` 0이거나 entry 자체가 없는 장비: "잠재능력 설정 불가"
  * `tucIgnoreForPotential`이 있는 경우 제외 (ex. 글로리온 링, 리부트 어웨이크 링, 이터널 플레임 링, 소울실드, 포스실드, 매그넘)
  * `exItem` 및 `exGrade`가 관련있어 보이기도 하는데 확실하지는 않음
  * 카르마 오브 등은 별 정보가 없지만 잠재능력 부여가 가능한데 이런 경우를 어떻게 판정할지 의문
* `fixedPotential` 설정된 장비: "에디셔널 잠재능력 설정 불가" (ex. 아이스바, 견습 도사, PC방 보상 도미네이터 펜던트, 오닉스 펜던트, 더 시드 엠블렘, 블랙 하트, 무릉 순위 보상 장갑, 오닉스 링, PC방 대여 특제 무기, PC방 보상 아케인셰이드 무기)

**Comment by OniOniOn-** [comment]
`noPotential` 설정시 잠재능력 설정 불가
보조무기, 엠블은 잠재능력 설정 가능
장비분류가 안드로이드, 메카닉 장비, 드래곤 장비면 잠재능력 설정 불가
