### ISSUE TITLE
안녕하세요. 파일 저장에 관하여 질문드립니다.

### ISSUE THREAD

**Issue by mabooky** [KENNYSOFT/WzComparerR2#9]
png 파일로 저장을 할 시에, 소스 이미지 이름이 _으로 시작한다든지, 중간에 :가 섞여있다든지 등의 Windows 파일 저장 규칙에 어긋나면 예외되지 않은 오류로 처리되어 진행이 불가능해집니다.
고쳐주시기를 바랍니다.

**Comment by KENNYSOFT** [comment]
안녕하세요. 소스 이미지 이름이라는 것이 무슨 뜻인가요?

**Comment by mabooky** [comment]
안녕하세요.
제 설명이 많이 부족했던 점 죄송합니다ㅠㅠ
증상에 대한 예를 들어볼게요 ㅎㅎ
메이플스토리의 Base.wz 파일을 열고, Base.wz\UI\UIWindow4\enchantUI(강화 UI 파일 폴더)에 들어가서, 그 안에 존재하는 이미지 파일을 저장하기 위해, 오른쪽 하단 즈음에 존재하는 그림 저장(이름을 정확하게 잘 모르겠습니다 ㅎㅎ Gif 설정인가 하는 버튼 옆에 있어요)을 눌렀을 때, 해당 그림의 이름의 이름에 :가 들어가거나, _로 시작하는 것과 같은 윈도우 운영 체제의 파일 저장 체계 규칙에 어긋나면 예외 처리되지 않은 오류라는 메세지를 퉤하고 뱉어냅니다. 예외 처리 해주시면 감사드리겠습니다. 또한 메이플스토리의 Data.wz 파일을 열었을 때에도 예외 처리되지 않은 오류가 나오는데, 제가 추측하기로는 암호화된 파일을 열었을 때 나는 오류에 예외 처리를 하지 않으신 것이라고 생각합니다.

부족한 글 끝까지 다 봐주셔서 감사드리고요, 모바일로 작성했기 때문에 다소 복잡할 수 있습니다. 추가 절차를 담은 스크린샷이나 동영상 캡처본 또는 추가 설명글이 필오하시면 This 이메일(mabooky@naver.com)으로 연락 주시기 바랍니다. 좋은 하루 되세용!-----Original Message-----

**Comment by mabooky** [comment]
# 추가 정보입니다:
이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.NotSupportedException: 지정한 경로 형식은 지원되지 않습니다.
   위치: System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   위치: System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   위치: System.IO.Path.GetFullPath(String path)
   위치: System.Drawing.IntSecurity.UnsafeGetFullPath(String fileName)
   위치: System.Drawing.IntSecurity.DemandWriteFileIO(String fileName)
   위치: System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   위치: System.Drawing.Image.Save(String filename, ImageFormat format)
   위치: WzComparerR2.MainForm.buttonItemSaveImage_Click(Object sender, EventArgs e)
   위치: DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
   위치: DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   위치: DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
   위치: DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
   위치: DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   위치: DevComponents.DotNetBar.ItemContainer.InternalMouseUp(MouseEventArgs objArg)
   위치: DevComponents.DotNetBar.ItemControl.OnMouseUp(MouseEventArgs e)
   위치: DevComponents.DotNetBar.RibbonBar.OnMouseUp(MouseEventArgs e)
   위치: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   위치: System.Windows.Forms.Control.WndProc(Message& m)
   위치: System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   위치: System.Windows.Forms.ContainerControl.WndProc(Message& m)
   위치: DevComponents.DotNetBar.ItemControl.WndProc(Message& m)
   위치: System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   위치: System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2110.0 built by: NET47REL1LAST
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WzComparerR2
    어셈블리 버전: 2.0.10.2
    Win32 버전: 2.0.10.70723
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/WzComparerR2.exe
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2110.0 built by: NET47REL1LAST
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2110.0 built by: NET47REL1LAST
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0 built by: NET47REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevComponents.DotNetBar2
    어셈블리 버전: 12.5.0.2
    Win32 버전: 12.5.0.2
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/DevComponents.DotNetBar2.DLL
----------------------------------------
WzComparerR2.PluginBase
    어셈블리 버전: 2.0.3.0
    Win32 버전: 2.0.3.70320
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/WzComparerR2.PluginBase.DLL
----------------------------------------
WzComparerR2.WzLib
    어셈블리 버전: 2.0.10.0
    Win32 버전: 2.0.10.70708
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/WzComparerR2.WzLib.DLL
----------------------------------------
WzComparerR2.Common
    어셈블리 버전: 2.0.10.1
    Win32 버전: 2.0.10.70802
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/WzComparerR2.Common.DLL
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0 built by: NET47REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2102.0 built by: NET47REL1LAST
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2102.0 built by: NET47REL1LAST
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MonoGame.Framework
    어셈블리 버전: 3.4.0.456
    Win32 버전: 3.4.0.456
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/MonoGame.Framework.DLL
----------------------------------------
Accessibility
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0 built by: NET47REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0 built by: NET47REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
SharpDX.Direct3D11
    어셈블리 버전: 2.5.1.0
    Win32 버전: 2.5.1
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/SharpDX.Direct3D11.DLL
----------------------------------------
SharpDX
    어셈블리 버전: 2.5.1.0
    Win32 버전: 2.5.1
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/SharpDX.DLL
----------------------------------------
SharpDX.DXGI
    어셈블리 버전: 2.5.1.0
    Win32 버전: 2.5.1
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/SharpDX.DXGI.DLL
----------------------------------------
spine-monogame
    어셈블리 버전: 1.0.0.1
    Win32 버전: 1.0.0.1
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/spine-monogame.DLL
----------------------------------------
System.Data
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2102.0 built by: NET47REL1LAST
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Bass.Net
    어셈블리 버전: 2.4.11.1
    Win32 버전: 2.4.11.1
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/Bass.Net.DLL
----------------------------------------
CharaSimResource
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/CharaSimResource.DLL
----------------------------------------
WzComparerR2.Avatar
    어셈블리 버전: 2.0.4.0
    Win32 버전: 2.0.4.70802
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/Plugin/WzComparerR2.Avatar/WzComparerR2.Avatar.dll
----------------------------------------
WzComparerR2.LuaConsole
    어셈블리 버전: 2.0.3.0
    Win32 버전: 2.0.3.70111
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/Plugin/WzComparerR2.LuaConsole/WzComparerR2.LuaConsole.dll
----------------------------------------
WzComparerR2.MapRender
    어셈블리 버전: 2.0.3.0
    Win32 버전: 2.0.3.70802
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/Plugin/WzComparerR2.MapRender/WzComparerR2.MapRender.DLL
----------------------------------------
ICSharpCode.TextEditor
    어셈블리 버전: 3.2.1.6466
    Win32 버전: 3.2.1.6466
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/Plugin/WzComparerR2.LuaConsole/ICSharpCode.TextEditor.DLL
----------------------------------------
EmptyKeys.UserInterface.Core
    어셈블리 버전: 2.6.0.0
    Win32 버전: 2.6.0.0
    코드베이스: file:///C:/Users/maboo/Downloads/KMS-v1.9.2.WzComparerR2/Plugin/WzComparerR2.MapRender/EmptyKeys.UserInterface.Core.DLL
----------------------------------------
System.Runtime
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Collections
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2046.0 built by: NET47REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.

**Comment by KENNYSOFT** [comment]
음, 중간에 코멘트가 하나 더 있었던 것 같은데 없어졌네요.. 그 내용도 읽긴 했었고, 지금 이 내용도 보니 자동저장과 관련된 이슈인 것으로 보입니다. 시간이 되는대로 확인해 보겠습니다. 늦어져서 죄송합니다.

현재 사라진 내용에 대해 그 중에 한 답변을 드리자면, Data.wz 파일의 경우 옛날에 사용되던 형식으로 현재는 아예 사용되지 않는 것으로 알고 있습니다. 실제로 파일 크기를 보시면 13바이트라 아무 내용도 없을 것 같이 생겼죠 ㅋㅋ

**Comment by mabooky** [comment]
죄송합니다 ㅠㅠ 자동 저장에 관한 것이라고 자세히 설명드리지 못했네요...
어쨌든 감사합니다. 빠른 시일 안에 해결되기를 간절히 원합니다.

**Comment by KENNYSOFT** [comment]
https://github.com/KENNYSOFT/WzComparerR2/commit/03fa664bf2dc0ee588cc0581d38ba12abb975691 에서 해결되었습니다.
