### ISSUE TITLE
저기 하리패커에서 kms wz파일 저장시 이미지 오프셋이 0이 되는 오류가 있습니다 ..

### ISSUE THREAD

**Issue by uper1126** [KENNYSOFT/WzComparerR2#90]
Harepacker MapleLib.WzLib.Wzfile에서 헤더에 데이터를 추가해야 된다는데, 도저히 해결방법을 모르겠어서 올립니다.. 죄송합니다 다른 프로그램인데 도움 좀 주시면 감사하겠습니다 ..

**Comment by KENNYSOFT** [comment]
아뇨
