### ISSUE TITLE
combine incAllStat, incMHP, incMMP

### ISSUE THREAD

**Issue by OniOniOn-** [KENNYSOFT/WzComparerR2#96]
인게임
![image](https://user-images.githubusercontent.com/6011621/156267205-adfe7d30-508c-456f-ac70-90c210fe373e.png)

시뮬
![image](https://user-images.githubusercontent.com/6011621/156267246-9f198e54-e1fa-496c-a8a5-cff35ac279bb.png)

올스탯, 최대 HP / 최대 MP를 한줄로 합쳐야 함

**Comment by KENNYSOFT** [comment]
제보 감사합니다. 저도 받고 확인하긴 했는데, * 50일 때에만 그런지 살펴봐야겠습니다.
