### ISSUE TITLE
훈장 미리보기 관련 문제

### ISSUE THREAD

**Issue by seotbeo** [KENNYSOFT/WzComparerR2#98]
1
![dddd](https://user-images.githubusercontent.com/101188238/159908494-cf93c100-ecb9-4b82-be73-f7a2fb89f75f.png)
(왼쪽: 위컴알, 오른쪽: 실제 인게임)
일부 옛날 훈장의 경우, KMS에서는 '의 훈장'이 이름 끝에 붙어있는데, 이 경우 인게임에서 제외하고 출력됩니다.

2 
![ddd](https://user-images.githubusercontent.com/101188238/159907787-87d71bc8-ffe7-4f93-861a-3f63880a2e75.png)
(왼쪽: 위컴알, 오른쪽: 실제 인게임)
UI/NameTag.img/medal에서 외형 이미지를 불러올 때
`GearGraphics.cs line 478~`처럼 c를 텍스트 너비에 맞춰 자르는게 아니라, 텍스트 너비보다 커지게 c를 최소한으로 붙여넣고 텍스트를 가운데 정렬하는 식으로 되어야 할 듯 합니다.

**Comment by KENNYSOFT** [comment]
감사합니다. 안그래도 https://www.inven.co.kr/board/maple/2304/30534 이 글 보고 좀 찾아봐야지 싶었어요
